### ISSUE TITLE
Switch to josharian/native for native endian?

### ISSUE THREAD

**Issue by bradfitz** [u-root/uio#7]
@hugelgupf, any chance this repo could switch to using https://pkg.go.dev/github.com/josharian/native

@josharian and I are trying to reduce the number of copies of this code in the Go ecosystem, per golang/go#57237

As of josharian/native#3 it has both a boolean const and a binary.ByteOrder var.

It also has a fallback to runtime-based detection if build tags get stale in the future.

If you're concerned about lacking control, I'm sure @josharian could grant you co-maintainership of the native repo.

Happy to send you a PR if you're cool with it. Or you can.

**Comment by bradfitz** [comment]
Oh, I guess we can't outright remove it, as it has a bunch of callers, like `github.com/insomniacslk/dhcp/dhcpv4` etc.

But you could use the constant in a `func init` which should get compiled away to ~nothing.

And you could update the docs to point people at the `native` package?

**Comment by josharian** [comment]
> I'm sure @josharian could grant you co-maintainership of the native repo

Indeed I could, just say the word.

**Comment by hugelgupf** [comment]
No need for co-maintainership, I'm happy with this. Thanks!

**Comment by hugelgupf** [comment]
If you go make a PR to update dhcp, I'll be happy to approve that as well.

**Comment by bradfitz** [comment]
> If you go make a PR to update dhcp, I'll be happy to approve that as well.

Done: https://github.com/insomniacslk/dhcp/pull/484
